### ISSUE TITLE
allow expressions without JS-files

### ISSUE THREAD

**Issue by ZeTo12** [AdamBien/enhydrator#27]
<columnExpression name="8">value.replaceAll(" ","")</columnExpression>

**Comment by ZeTo12** [comment]
<columnExpression name="13">
            var SimpleDateFormat = Java.type("java.text.SimpleDateFormat");
            var formatter = new SimpleDateFormat("dd-MM-yyyy");
            formatter.setTimeZone(java.util.TimeZone.getTimeZone("Europe/Copenhagen"));
            var date = formatter.parse(value);
            return date;
    </columnExpression>

**Comment by AdamBien** [comment]
Is going to be implemented in 0.0.7 (soon)

**Comment by AdamBien** [comment]
It works like this:

function execute(column){return prefix + ' ' + column}

So far you have to specify the function body. We could skip that (=provide default body), but then the name of the parameter would be unclear.

**Comment by AdamBien** [comment]
See
